Repository ITU-BDSA2024-GROUP22/Chirp, pull requests merged in 2024-12, with the labels that each got.

#233 GitHub mailfix
  src/Chirp.Web/Areas/Identity/Pages/Account/ExternalLogin.cshtml
  src/Chirp.Web/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
  src/Chirp.Web/Program.cs
Labels: enhancement

#260 Added information to users loggin in with github
  src/Chirp.Core/Interfaces/ICheepRepository.cs
  src/Chirp.Infrastructure/Repositories/CheepRepository.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Login.cshtml
  src/Chirp.Web/Areas/Identity/Pages/Account/Register.cshtml
Labels: enhancement

#268 Cleanup
  PlaywrightTests/GetAuthorTest.cs
  PlaywrightTests/UiTest.cs
  src/Chirp.Core/Interfaces/ICheepRepository.cs
  src/Chirp.Infrastructure/Repositories/CheepRepository.cs
  src/Chirp.Infrastructure/Repositories/FollowRepository.cs
  src/Chirp.Infrastructure/Services/CheepService.cs
  src/Chirp.Web/wwwroot/uploads/f4053829-d60d-4c85-81f3-fec2a9706e2e_RÆV.webp
  test/Chirp.Tests/AuthorTest.cs
  test/Chirp.Tests/CheepRepositoryTest.cs
  test/Chirp.Tests/CheepTest.cs
  test/Chirp.Tests/FollowRepositoryTest.cs
Labels: clean uo

#272 More Unit testing
  src/Chirp.Web/wwwroot/uploads/e4844fd5-4f94-4702-9098-596319c47cb3_LØVE.jpg
  test/Chirp.Tests/CheepRepositoryTest.cs
  test/Chirp.Tests/FollowRepositoryTest.cs
Labels: testing

#285 Moved httpsredirection in program.cs
  src/Chirp.Web/Program.cs
  src/Chirp.Web/wwwroot/uploads/0ded479a-b794-478d-9334-49092d964a0f_LØVE.jpg
Labels: clean uo

#289 the style of the 'forget me' bustton has been changed
  src/Chirp.Web/Pages/AboutMe.cshtml
Labels: enhancement

#294 Minor bug fixed
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
Labels: bug

#298 Minor fix
  src/Chirp.Infrastructure/DbInitializer.cs
  src/Chirp.Web/wwwroot/uploads/032c0622-7e58-4bda-97a7-785b40f3262d_giphy.webp
  src/Chirp.Web/wwwroot/uploads/0ded479a-b794-478d-9334-49092d964a0f_LØVE.jpg
  src/Chirp.Web/wwwroot/uploads/2bd54291-560b-4981-ac7c-a7726cd46fab_Screenshot 2024-11-26 at 14.18.23.png
  src/Chirp.Web/wwwroot/uploads/43b1d5b2-11fc-401c-a714-907e9f174ce9_peach.png
  src/Chirp.Web/wwwroot/uploads/443f83da-e75a-42e4-9774-aedb64699201_luigi.png
  src/Chirp.Web/wwwroot/uploads/4b99464f-4fd9-4750-8bf6-eb0b1bfccc46_chaos-elmo-fire.gif
  src/Chirp.Web/wwwroot/uploads/5d674af6-2778-4e1f-a8af-474b090ca3a5_Skærmbillede 2024-12-03 kl. 23.43.41.png
  src/Chirp.Web/wwwroot/uploads/70107445-5528-438b-aa6d-1da39820d4dc_hvalpefedt-2.jpg
  src/Chirp.Web/wwwroot/uploads/75d30c20-ff8c-49eb-9436-b182c8c0f772_luigi.png
  src/Chirp.Web/wwwroot/uploads/796a6c32-a4a3-4795-922c-bdf15299ce4d_Screenshot 2024-11-26 at 14.18.23.png
  src/Chirp.Web/wwwroot/uploads/7cdbd165-c932-421a-843f-d5e8a46da7ca_peach.png
  src/Chirp.Web/wwwroot/uploads/8b418452-2b6b-497c-9851-e2fc811e8244_shrek.jpg
  src/Chirp.Web/wwwroot/uploads/8f110b31-4ba2-4e82-b253-74639131b68a_birthy.jpg
  src/Chirp.Web/wwwroot/uploads/9e9d3949-2917-429a-8f47-be5e448872dd_462564364_1284305802759556_6599011227439368120_n.png
  src/Chirp.Web/wwwroot/uploads/a2eaf18f-b4fb-4c42-b473-ab771118047b_shrek.jpg
  src/Chirp.Web/wwwroot/uploads/b7fd2970-4c21-47ea-8c15-e849170c5f31_peach.png
  src/Chirp.Web/wwwroot/uploads/bb9a34cc-a213-4b30-bdb5-dd604a66c55a_peach.png
  src/Chirp.Web/wwwroot/uploads/c4eb50c1-34b1-44af-a602-cf782dfb3da2_462564364_1284305802759556_6599011227439368120_n.png
  src/Chirp.Web/wwwroot/uploads/cf832f4e-066a-449e-8bd1-2701f7904edb_LØVE.jpg
  src/Chirp.Web/wwwroot/uploads/eae43c50-72fa-4b84-b788-5b3ca72e59a6_RÆV.webp
  src/Chirp.Web/wwwroot/uploads/f4053829-d60d-4c85-81f3-fec2a9706e2e_RÆV.webp
  test/Chirp.Tests/IntegrationTests.cs
Labels: clean uo
